In [20]:
import pandas as pd
car = pd.read_csv("rent_car_data.csv", header=None)
car

,0,1,2,3,4,5,6,7,8,9,10,11,12
0,0,FUKUOKA,후쿠오카%20공항(FUK),도요타 아쿠아 또는 동급차종,TOYOTA_FUKUOKA 나가하마 하카타항점,2023-07-26,2023-07-27,휘발유,소형,5인,오토,면책커버보험 포함,"84,940원"
1,1,FUKUOKA,후쿠오카%20공항(FUK),도요타 프리우스 또는 동급차종,TOYOTA_FUKUOKA 나가하마 하카타항점,2023-07-26,2023-07-27,휘발유,준중형,5인,오토,면책커버보험 포함,"101,510원"
2,2,FUKUOKA,후쿠오카%20공항(FUK),혼다 스텝왜건 또는 동급차종,니폰 렌터카,2023-07-26,2023-07-27,NaN,RV,7인,오토,스탠다드플랜 포함,"248,560원"
3,3,FUKUOKA,후쿠오카%20공항(FUK),도요타 아쿠아 또는 동급차종,TOYOTA_FUKUOKA 후쿠오카공항 국제선점,2023-07-27,2023-07-28,휘발유,소형,5인,오토,면책커버보험 포함,"84,940원"
4,4,FUKUOKA,후쿠오카%20공항(FUK),도요타 프리우스 또는 동급차종,TOYOTA_FUKUOKA 나가하마 하카타항점,2023-07-29,2023-07-30,휘발유,준중형,5인,오토,면책커버보험 포함,"101,510원"
...,...,...,...,...,...,...,...,...,...,...,...,...,...
3754,3754,SAPPORO,신치토세%20공항(CTS),도요타 프리우스 또는 동급차종,TOYOTA_SAPPORO 신치토세공항 스즈란점,2023-09-29,2023-09-30,휘발유,준중형,5인,오토,면책커버보험 포함,"101,510~138,730원"
3755,3755,SAPPORO,신치토세%20공항(CTS),도요타 시엔타 또는 동급차종,TOYOTA_SAPPORO 신치토세공항 스즈란점,2023-09-29,2023-09-30,휘발유,RV,5인,오토,면책커버보험 포함,"110,710원"
3756,3756,SAPPORO,신치토세%20공항(CTS),스바루 임프레자 또는 동급차종,니폰 렌터카,2023-09-29,2023-09-30,NaN,준중형,5인,오토,프리미엄플랜 포함,"112,450원"
3757,3757,SAPPORO,신치토세%20공항(CTS),닛산 노트 E-파워 또는 동급차종,니폰 렌터카,2023-09-29,2023-09-30,NaN,소형,5인,오토,프리미엄플랜 포함,"119,300원"
3758,3758,SAPPORO,신치토세%20공항(CTS),도요타 복시 또는 동급차종,TOYOTA_SAPPORO 신치토세공항 스즈란점,2023-09-29,2023-09-30,휘발유,RV,7인,오토,면책커버보험 포함,"138,330~175,160원"

In [21]:
car = car.drop(columns=car.columns[0])
car

,1,2,3,4,5,6,7,8,9,10,11,12
0,FUKUOKA,후쿠오카%20공항(FUK),도요타 아쿠아 또는 동급차종,TOYOTA_FUKUOKA 나가하마 하카타항점,2023-07-26,2023-07-27,휘발유,소형,5인,오토,면책커버보험 포함,"84,940원"
1,FUKUOKA,후쿠오카%20공항(FUK),도요타 프리우스 또는 동급차종,TOYOTA_FUKUOKA 나가하마 하카타항점,2023-07-26,2023-07-27,휘발유,준중형,5인,오토,면책커버보험 포함,"101,510원"
2,FUKUOKA,후쿠오카%20공항(FUK),혼다 스텝왜건 또는 동급차종,니폰 렌터카,2023-07-26,2023-07-27,NaN,RV,7인,오토,스탠다드플랜 포함,"248,560원"
3,FUKUOKA,후쿠오카%20공항(FUK),도요타 아쿠아 또는 동급차종,TOYOTA_FUKUOKA 후쿠오카공항 국제선점,2023-07-27,2023-07-28,휘발유,소형,5인,오토,면책커버보험 포함,"84,940원"
4,FUKUOKA,후쿠오카%20공항(FUK),도요타 프리우스 또는 동급차종,TOYOTA_FUKUOKA 나가하마 하카타항점,2023-07-29,2023-07-30,휘발유,준중형,5인,오토,면책커버보험 포함,"101,510원"
...,...,...,...,...,...,...,...,...,...,...,...,...
3754,SAPPORO,신치토세%20공항(CTS),도요타 프리우스 또는 동급차종,TOYOTA_SAPPORO 신치토세공항 스즈란점,2023-09-29,2023-09-30,휘발유,준중형,5인,오토,면책커버보험 포함,"101,510~138,730원"
3755,SAPPORO,신치토세%20공항(CTS),도요타 시엔타 또는 동급차종,TOYOTA_SAPPORO 신치토세공항 스즈란점,2023-09-29,2023-09-30,휘발유,RV,5인,오토,면책커버보험 포함,"110,710원"
3756,SAPPORO,신치토세%20공항(CTS),스바루 임프레자 또는 동급차종,니폰 렌터카,2023-09-29,2023-09-30,NaN,준중형,5인,오토,프리미엄플랜 포함,"112,450원"
3757,SAPPORO,신치토세%20공항(CTS),닛산 노트 E-파워 또는 동급차종,니폰 렌터카,2023-09-29,2023-09-30,NaN,소형,5인,오토,프리미엄플랜 포함,"119,300원"
3758,SAPPORO,신치토세%20공항(CTS),도요타 복시 또는 동급차종,TOYOTA_SAPPORO 신치토세공항 스즈란점,2023-09-29,2023-09-30,휘발유,RV,7인,오토,면책커버보험 포함,"138,330~175,160원"

In [22]:
col_list = ['지역','공항','이름','회사','대여일','반납일','오일','크기','제한인원수','기어','보험','가격']

In [23]:
car.columns = col_list
car

,지역,공항,이름,회사,대여일,반납일,오일,크기,제한인원수,기어,보험,가격
0,FUKUOKA,후쿠오카%20공항(FUK),도요타 아쿠아 또는 동급차종,TOYOTA_FUKUOKA 나가하마 하카타항점,2023-07-26,2023-07-27,휘발유,소형,5인,오토,면책커버보험 포함,"84,940원"
1,FUKUOKA,후쿠오카%20공항(FUK),도요타 프리우스 또는 동급차종,TOYOTA_FUKUOKA 나가하마 하카타항점,2023-07-26,2023-07-27,휘발유,준중형,5인,오토,면책커버보험 포함,"101,510원"
2,FUKUOKA,후쿠오카%20공항(FUK),혼다 스텝왜건 또는 동급차종,니폰 렌터카,2023-07-26,2023-07-27,NaN,RV,7인,오토,스탠다드플랜 포함,"248,560원"
3,FUKUOKA,후쿠오카%20공항(FUK),도요타 아쿠아 또는 동급차종,TOYOTA_FUKUOKA 후쿠오카공항 국제선점,2023-07-27,2023-07-28,휘발유,소형,5인,오토,면책커버보험 포함,"84,940원"
4,FUKUOKA,후쿠오카%20공항(FUK),도요타 프리우스 또는 동급차종,TOYOTA_FUKUOKA 나가하마 하카타항점,2023-07-29,2023-07-30,휘발유,준중형,5인,오토,면책커버보험 포함,"101,510원"
...,...,...,...,...,...,...,...,...,...,...,...,...
3754,SAPPORO,신치토세%20공항(CTS),도요타 프리우스 또는 동급차종,TOYOTA_SAPPORO 신치토세공항 스즈란점,2023-09-29,2023-09-30,휘발유,준중형,5인,오토,면책커버보험 포함,"101,510~138,730원"
3755,SAPPORO,신치토세%20공항(CTS),도요타 시엔타 또는 동급차종,TOYOTA_SAPPORO 신치토세공항 스즈란점,2023-09-29,2023-09-30,휘발유,RV,5인,오토,면책커버보험 포함,"110,710원"
3756,SAPPORO,신치토세%20공항(CTS),스바루 임프레자 또는 동급차종,니폰 렌터카,2023-09-29,2023-09-30,NaN,준중형,5인,오토,프리미엄플랜 포함,"112,450원"
3757,SAPPORO,신치토세%20공항(CTS),닛산 노트 E-파워 또는 동급차종,니폰 렌터카,2023-09-29,2023-09-30,NaN,소형,5인,오토,프리미엄플랜 포함,"119,300원"
3758,SAPPORO,신치토세%20공항(CTS),도요타 복시 또는 동급차종,TOYOTA_SAPPORO 신치토세공항 스즈란점,2023-09-29,2023-09-30,휘발유,RV,7인,오토,면책커버보험 포함,"138,330~175,160원"

In [24]:
car.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3759 entries, 0 to 3758
Data columns (total 12 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   지역      3759 non-null   object
 1   공항      3759 non-null   object
 2   이름      3759 non-null   object
 3   회사      3759 non-null   object
 4   대여일     3759 non-null   object
 5   반납일     3759 non-null   object
 6   오일      2448 non-null   object
 7   크기      3759 non-null   object
 8   제한인원수   3759 non-null   object
 9   기어      3759 non-null   object
 10  보험      3759 non-null   object
 11  가격      3759 non-null   object
dtypes: object(12)
memory usage: 352.5+ KB

In [25]:
car.isna().sum()

지역          0
공항          0
이름          0
회사          0
대여일         0
반납일         0
오일       1311
크기          0
제한인원수       0
기어          0
보험          0
가격          0
dtype: int64

In [26]:
#오일 결측치는 휘발유로 대체
car.loc[car['오일'].isna(), '오일'] = '휘발유'
car

,지역,공항,이름,회사,대여일,반납일,오일,크기,제한인원수,기어,보험,가격
0,FUKUOKA,후쿠오카%20공항(FUK),도요타 아쿠아 또는 동급차종,TOYOTA_FUKUOKA 나가하마 하카타항점,2023-07-26,2023-07-27,휘발유,소형,5인,오토,면책커버보험 포함,"84,940원"
1,FUKUOKA,후쿠오카%20공항(FUK),도요타 프리우스 또는 동급차종,TOYOTA_FUKUOKA 나가하마 하카타항점,2023-07-26,2023-07-27,휘발유,준중형,5인,오토,면책커버보험 포함,"101,510원"
2,FUKUOKA,후쿠오카%20공항(FUK),혼다 스텝왜건 또는 동급차종,니폰 렌터카,2023-07-26,2023-07-27,휘발유,RV,7인,오토,스탠다드플랜 포함,"248,560원"
3,FUKUOKA,후쿠오카%20공항(FUK),도요타 아쿠아 또는 동급차종,TOYOTA_FUKUOKA 후쿠오카공항 국제선점,2023-07-27,2023-07-28,휘발유,소형,5인,오토,면책커버보험 포함,"84,940원"
4,FUKUOKA,후쿠오카%20공항(FUK),도요타 프리우스 또는 동급차종,TOYOTA_FUKUOKA 나가하마 하카타항점,2023-07-29,2023-07-30,휘발유,준중형,5인,오토,면책커버보험 포함,"101,510원"
...,...,...,...,...,...,...,...,...,...,...,...,...
3754,SAPPORO,신치토세%20공항(CTS),도요타 프리우스 또는 동급차종,TOYOTA_SAPPORO 신치토세공항 스즈란점,2023-09-29,2023-09-30,휘발유,준중형,5인,오토,면책커버보험 포함,"101,510~138,730원"
3755,SAPPORO,신치토세%20공항(CTS),도요타 시엔타 또는 동급차종,TOYOTA_SAPPORO 신치토세공항 스즈란점,2023-09-29,2023-09-30,휘발유,RV,5인,오토,면책커버보험 포함,"110,710원"
3756,SAPPORO,신치토세%20공항(CTS),스바루 임프레자 또는 동급차종,니폰 렌터카,2023-09-29,2023-09-30,휘발유,준중형,5인,오토,프리미엄플랜 포함,"112,450원"
3757,SAPPORO,신치토세%20공항(CTS),닛산 노트 E-파워 또는 동급차종,니폰 렌터카,2023-09-29,2023-09-30,휘발유,소형,5인,오토,프리미엄플랜 포함,"119,300원"
3758,SAPPORO,신치토세%20공항(CTS),도요타 복시 또는 동급차종,TOYOTA_SAPPORO 신치토세공항 스즈란점,2023-09-29,2023-09-30,휘발유,RV,7인,오토,면책커버보험 포함,"138,330~175,160원"

In [27]:
car['공항'].unique()

array(['후쿠오카%20공항(FUK)', '기타큐슈%20공항(KKJ)', '나하%20공항(OKA)',
       '나리타%20국제공항(NRT)', '도쿄%20하네다%20국제공항(HND)', '간사이%20국제공항(KIX)',
       '신치토세%20공항(CTS)'], dtype=object)

In [28]:
car['공항'] = car['공항'].str.extract(r'\((.*?)\)')
car

,지역,공항,이름,회사,대여일,반납일,오일,크기,제한인원수,기어,보험,가격
0,FUKUOKA,FUK,도요타 아쿠아 또는 동급차종,TOYOTA_FUKUOKA 나가하마 하카타항점,2023-07-26,2023-07-27,휘발유,소형,5인,오토,면책커버보험 포함,"84,940원"
1,FUKUOKA,FUK,도요타 프리우스 또는 동급차종,TOYOTA_FUKUOKA 나가하마 하카타항점,2023-07-26,2023-07-27,휘발유,준중형,5인,오토,면책커버보험 포함,"101,510원"
2,FUKUOKA,FUK,혼다 스텝왜건 또는 동급차종,니폰 렌터카,2023-07-26,2023-07-27,휘발유,RV,7인,오토,스탠다드플랜 포함,"248,560원"
3,FUKUOKA,FUK,도요타 아쿠아 또는 동급차종,TOYOTA_FUKUOKA 후쿠오카공항 국제선점,2023-07-27,2023-07-28,휘발유,소형,5인,오토,면책커버보험 포함,"84,940원"
4,FUKUOKA,FUK,도요타 프리우스 또는 동급차종,TOYOTA_FUKUOKA 나가하마 하카타항점,2023-07-29,2023-07-30,휘발유,준중형,5인,오토,면책커버보험 포함,"101,510원"
...,...,...,...,...,...,...,...,...,...,...,...,...
3754,SAPPORO,CTS,도요타 프리우스 또는 동급차종,TOYOTA_SAPPORO 신치토세공항 스즈란점,2023-09-29,2023-09-30,휘발유,준중형,5인,오토,면책커버보험 포함,"101,510~138,730원"
3755,SAPPORO,CTS,도요타 시엔타 또는 동급차종,TOYOTA_SAPPORO 신치토세공항 스즈란점,2023-09-29,2023-09-30,휘발유,RV,5인,오토,면책커버보험 포함,"110,710원"
3756,SAPPORO,CTS,스바루 임프레자 또는 동급차종,니폰 렌터카,2023-09-29,2023-09-30,휘발유,준중형,5인,오토,프리미엄플랜 포함,"112,450원"
3757,SAPPORO,CTS,닛산 노트 E-파워 또는 동급차종,니폰 렌터카,2023-09-29,2023-09-30,휘발유,소형,5인,오토,프리미엄플랜 포함,"119,300원"
3758,SAPPORO,CTS,도요타 복시 또는 동급차종,TOYOTA_SAPPORO 신치토세공항 스즈란점,2023-09-29,2023-09-30,휘발유,RV,7인,오토,면책커버보험 포함,"138,330~175,160원"

In [29]:
car[['브랜드', '이름']] = car['이름'].str.split(' ', n=1, expand=True)
car['이름'] = car['이름'].str.replace(' 또는 동급차종', '')
car

,지역,공항,이름,회사,대여일,반납일,오일,크기,제한인원수,기어,보험,가격,브랜드
0,FUKUOKA,FUK,아쿠아,TOYOTA_FUKUOKA 나가하마 하카타항점,2023-07-26,2023-07-27,휘발유,소형,5인,오토,면책커버보험 포함,"84,940원",도요타
1,FUKUOKA,FUK,프리우스,TOYOTA_FUKUOKA 나가하마 하카타항점,2023-07-26,2023-07-27,휘발유,준중형,5인,오토,면책커버보험 포함,"101,510원",도요타
2,FUKUOKA,FUK,스텝왜건,니폰 렌터카,2023-07-26,2023-07-27,휘발유,RV,7인,오토,스탠다드플랜 포함,"248,560원",혼다
3,FUKUOKA,FUK,아쿠아,TOYOTA_FUKUOKA 후쿠오카공항 국제선점,2023-07-27,2023-07-28,휘발유,소형,5인,오토,면책커버보험 포함,"84,940원",도요타
4,FUKUOKA,FUK,프리우스,TOYOTA_FUKUOKA 나가하마 하카타항점,2023-07-29,2023-07-30,휘발유,준중형,5인,오토,면책커버보험 포함,"101,510원",도요타
...,...,...,...,...,...,...,...,...,...,...,...,...,...
3754,SAPPORO,CTS,프리우스,TOYOTA_SAPPORO 신치토세공항 스즈란점,2023-09-29,2023-09-30,휘발유,준중형,5인,오토,면책커버보험 포함,"101,510~138,730원",도요타
3755,SAPPORO,CTS,시엔타,TOYOTA_SAPPORO 신치토세공항 스즈란점,2023-09-29,2023-09-30,휘발유,RV,5인,오토,면책커버보험 포함,"110,710원",도요타
3756,SAPPORO,CTS,임프레자,니폰 렌터카,2023-09-29,2023-09-30,휘발유,준중형,5인,오토,프리미엄플랜 포함,"112,450원",스바루
3757,SAPPORO,CTS,노트 E-파워,니폰 렌터카,2023-09-29,2023-09-30,휘발유,소형,5인,오토,프리미엄플랜 포함,"119,300원",닛산
3758,SAPPORO,CTS,복시,TOYOTA_SAPPORO 신치토세공항 스즈란점,2023-09-29,2023-09-30,휘발유,RV,7인,오토,면책커버보험 포함,"138,330~175,160원",도요타

In [30]:
car['가격'] = car['가격'].str.replace(',', '').str.extract(r'(\d+)').astype(int)
car

,지역,공항,이름,회사,대여일,반납일,오일,크기,제한인원수,기어,보험,가격,브랜드
0,FUKUOKA,FUK,아쿠아,TOYOTA_FUKUOKA 나가하마 하카타항점,2023-07-26,2023-07-27,휘발유,소형,5인,오토,면책커버보험 포함,84940,도요타
1,FUKUOKA,FUK,프리우스,TOYOTA_FUKUOKA 나가하마 하카타항점,2023-07-26,2023-07-27,휘발유,준중형,5인,오토,면책커버보험 포함,101510,도요타
2,FUKUOKA,FUK,스텝왜건,니폰 렌터카,2023-07-26,2023-07-27,휘발유,RV,7인,오토,스탠다드플랜 포함,248560,혼다
3,FUKUOKA,FUK,아쿠아,TOYOTA_FUKUOKA 후쿠오카공항 국제선점,2023-07-27,2023-07-28,휘발유,소형,5인,오토,면책커버보험 포함,84940,도요타
4,FUKUOKA,FUK,프리우스,TOYOTA_FUKUOKA 나가하마 하카타항점,2023-07-29,2023-07-30,휘발유,준중형,5인,오토,면책커버보험 포함,101510,도요타
...,...,...,...,...,...,...,...,...,...,...,...,...,...
3754,SAPPORO,CTS,프리우스,TOYOTA_SAPPORO 신치토세공항 스즈란점,2023-09-29,2023-09-30,휘발유,준중형,5인,오토,면책커버보험 포함,101510,도요타
3755,SAPPORO,CTS,시엔타,TOYOTA_SAPPORO 신치토세공항 스즈란점,2023-09-29,2023-09-30,휘발유,RV,5인,오토,면책커버보험 포함,110710,도요타
3756,SAPPORO,CTS,임프레자,니폰 렌터카,2023-09-29,2023-09-30,휘발유,준중형,5인,오토,프리미엄플랜 포함,112450,스바루
3757,SAPPORO,CTS,노트 E-파워,니폰 렌터카,2023-09-29,2023-09-30,휘발유,소형,5인,오토,프리미엄플랜 포함,119300,닛산
3758,SAPPORO,CTS,복시,TOYOTA_SAPPORO 신치토세공항 스즈란점,2023-09-29,2023-09-30,휘발유,RV,7인,오토,면책커버보험 포함,138330,도요타

In [31]:
car=car.drop(['회사', '오일', '기어'], axis=1)
car

,지역,공항,이름,대여일,반납일,크기,제한인원수,보험,가격,브랜드
0,FUKUOKA,FUK,아쿠아,2023-07-26,2023-07-27,소형,5인,면책커버보험 포함,84940,도요타
1,FUKUOKA,FUK,프리우스,2023-07-26,2023-07-27,준중형,5인,면책커버보험 포함,101510,도요타
2,FUKUOKA,FUK,스텝왜건,2023-07-26,2023-07-27,RV,7인,스탠다드플랜 포함,248560,혼다
3,FUKUOKA,FUK,아쿠아,2023-07-27,2023-07-28,소형,5인,면책커버보험 포함,84940,도요타
4,FUKUOKA,FUK,프리우스,2023-07-29,2023-07-30,준중형,5인,면책커버보험 포함,101510,도요타
...,...,...,...,...,...,...,...,...,...,...
3754,SAPPORO,CTS,프리우스,2023-09-29,2023-09-30,준중형,5인,면책커버보험 포함,101510,도요타
3755,SAPPORO,CTS,시엔타,2023-09-29,2023-09-30,RV,5인,면책커버보험 포함,110710,도요타
3756,SAPPORO,CTS,임프레자,2023-09-29,2023-09-30,준중형,5인,프리미엄플랜 포함,112450,스바루
3757,SAPPORO,CTS,노트 E-파워,2023-09-29,2023-09-30,소형,5인,프리미엄플랜 포함,119300,닛산
3758,SAPPORO,CTS,복시,2023-09-29,2023-09-30,RV,7인,면책커버보험 포함,138330,도요타

In [32]:
car['제한인원수'] = car['제한인원수'].str.extract(r'(\d+)').astype(int)
car

,지역,공항,이름,대여일,반납일,크기,제한인원수,보험,가격,브랜드
0,FUKUOKA,FUK,아쿠아,2023-07-26,2023-07-27,소형,5,면책커버보험 포함,84940,도요타
1,FUKUOKA,FUK,프리우스,2023-07-26,2023-07-27,준중형,5,면책커버보험 포함,101510,도요타
2,FUKUOKA,FUK,스텝왜건,2023-07-26,2023-07-27,RV,7,스탠다드플랜 포함,248560,혼다
3,FUKUOKA,FUK,아쿠아,2023-07-27,2023-07-28,소형,5,면책커버보험 포함,84940,도요타
4,FUKUOKA,FUK,프리우스,2023-07-29,2023-07-30,준중형,5,면책커버보험 포함,101510,도요타
...,...,...,...,...,...,...,...,...,...,...
3754,SAPPORO,CTS,프리우스,2023-09-29,2023-09-30,준중형,5,면책커버보험 포함,101510,도요타
3755,SAPPORO,CTS,시엔타,2023-09-29,2023-09-30,RV,5,면책커버보험 포함,110710,도요타
3756,SAPPORO,CTS,임프레자,2023-09-29,2023-09-30,준중형,5,프리미엄플랜 포함,112450,스바루
3757,SAPPORO,CTS,노트 E-파워,2023-09-29,2023-09-30,소형,5,프리미엄플랜 포함,119300,닛산
3758,SAPPORO,CTS,복시,2023-09-29,2023-09-30,RV,7,면책커버보험 포함,138330,도요타

In [33]:
car['제한인원수']

0       5
1       5
2       7
3       5
4       5
       ..
3754    5
3755    5
3756    5
3757    5
3758    7
Name: 제한인원수, Length: 3759, dtype: int32

In [34]:
# Convert '제한인원수' column to integers and filter the cars with a maximum passenger capacity of 7
filtered_cars = car[car['제한인원수'] == 7]

# Remove duplicates and print the names of unique cars
unique_car_names = filtered_cars['이름'].drop_duplicates()
for car_name in unique_car_names:
    print(car_name)

스텝왜건
알파드
복시

In [35]:
# Convert '제한인원수' column to integers and filter the cars with a maximum passenger capacity of 7
filtered_cars = car[car['제한인원수'] == 10]

# Remove duplicates and print the names of unique cars
unique_car_names = filtered_cars['이름'].drop_duplicates()
for car_name in unique_car_names:
    print(car_name)

하이에이스 그랜드 캐빈

In [36]:
car['대여일'] = car['대여일'].str.replace('-','').astype(int)
car['반납일'] = car['반납일'].str.replace('-','').astype(int)
car

,지역,공항,이름,대여일,반납일,크기,제한인원수,보험,가격,브랜드
0,FUKUOKA,FUK,아쿠아,20230726,20230727,소형,5,면책커버보험 포함,84940,도요타
1,FUKUOKA,FUK,프리우스,20230726,20230727,준중형,5,면책커버보험 포함,101510,도요타
2,FUKUOKA,FUK,스텝왜건,20230726,20230727,RV,7,스탠다드플랜 포함,248560,혼다
3,FUKUOKA,FUK,아쿠아,20230727,20230728,소형,5,면책커버보험 포함,84940,도요타
4,FUKUOKA,FUK,프리우스,20230729,20230730,준중형,5,면책커버보험 포함,101510,도요타
...,...,...,...,...,...,...,...,...,...,...
3754,SAPPORO,CTS,프리우스,20230929,20230930,준중형,5,면책커버보험 포함,101510,도요타
3755,SAPPORO,CTS,시엔타,20230929,20230930,RV,5,면책커버보험 포함,110710,도요타
3756,SAPPORO,CTS,임프레자,20230929,20230930,준중형,5,프리미엄플랜 포함,112450,스바루
3757,SAPPORO,CTS,노트 E-파워,20230929,20230930,소형,5,프리미엄플랜 포함,119300,닛산
3758,SAPPORO,CTS,복시,20230929,20230930,RV,7,면책커버보험 포함,138330,도요타

In [37]:
# Define a dictionary to map English names to Korean names
english_to_korean = {
    'FUKUOKA': '후쿠오카',
    'OKINAWA': '오키나와',
    'OSAKA': '오사카',
    'SAPPORO': '삿포로',
    'TOKYO': '도쿄'
}

# Convert the values in the '지역' column from English to Korean
car['지역'] = car['지역'].map(english_to_korean)

In [38]:
# Assuming you have a DataFrame called 'data'
cols = ['지역', '공항', '이름', '크기', '보험', '브랜드']

# Print unique values for each column in 'data'
for col in cols:
    unique_values = car[col].unique()
    unique_values.sort()  # Sort the unique values for each column
    print(f"Unique values in '{col}': {unique_values}")

Unique values in '지역': ['도쿄' '삿포로' '오사카' '오키나와' '후쿠오카']
Unique values in '공항': ['CTS' 'FUK' 'HND' 'KIX' 'KKJ' 'NRT' 'OKA']
Unique values in '이름': ['86' 'C-HR' 'eK 왜건' '노트 5도어' '노트 E-파워' '데미오' '델리카 8인승' '라이즈' '랜드 크루저 프라도'
 '레보그' '루미' '무브 콘테' '벨파이어 8인승' '복시' '비츠' '스마일' '스텝왜건' '스텝왜건 8인승' '시엔타'
 '시엔타 6인승' '아쿠아' '알파드' '알파드 8인승' '야리스' '엔박스' '왜건 R' '이클립스 크로스' '임프레자' '캠리'
 '코롤라' '코롤라 필더' '큐브' '크라운' '태프트' '프리우스' '피트' '하이에이스 그랜드 캐빈' '허슬러']
Unique values in '크기': ['RV' 'SUV' '경형' '대형' '소형' '왜건' '준중형' '중형']
Unique values in '보험': ['면책커버보험 포함' '스탠다드플랜 포함' '프리미엄플랜 포함']
Unique values in '브랜드': ['닛산' '다이하쓰' '도요타' '마쯔다' '미쓰비시' '스바루' '스즈키' '혼다']

In [39]:
car

,지역,공항,이름,대여일,반납일,크기,제한인원수,보험,가격,브랜드
0,후쿠오카,FUK,아쿠아,20230726,20230727,소형,5,면책커버보험 포함,84940,도요타
1,후쿠오카,FUK,프리우스,20230726,20230727,준중형,5,면책커버보험 포함,101510,도요타
2,후쿠오카,FUK,스텝왜건,20230726,20230727,RV,7,스탠다드플랜 포함,248560,혼다
3,후쿠오카,FUK,아쿠아,20230727,20230728,소형,5,면책커버보험 포함,84940,도요타
4,후쿠오카,FUK,프리우스,20230729,20230730,준중형,5,면책커버보험 포함,101510,도요타
...,...,...,...,...,...,...,...,...,...,...
3754,삿포로,CTS,프리우스,20230929,20230930,준중형,5,면책커버보험 포함,101510,도요타
3755,삿포로,CTS,시엔타,20230929,20230930,RV,5,면책커버보험 포함,110710,도요타
3756,삿포로,CTS,임프레자,20230929,20230930,준중형,5,프리미엄플랜 포함,112450,스바루
3757,삿포로,CTS,노트 E-파워,20230929,20230930,소형,5,프리미엄플랜 포함,119300,닛산
3758,삿포로,CTS,복시,20230929,20230930,RV,7,면책커버보험 포함,138330,도요타

In [40]:
car.to_csv('car_total.csv', index=False, encoding='utf-8-sig')

In [41]:
import pandas as pd
from sklearn.preprocessing import OrdinalEncoder
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import train_test_split
from sklearn.metrics import *

# 데이터프레임의 '크기', '제한인원수', '보험', '브랜드' 열을 오디널 인코딩합니다.
encoder = OrdinalEncoder()
ordinal_cols = ['지역',	'공항',	'이름',	'크기',	'보험',	'브랜드']
car[ordinal_cols] = encoder.fit_transform(car[ordinal_cols])

# 독립 변수(X)와 종속 변수(y)를 나눕니다.
X = car.drop(['가격'], axis=1)
y = car['가격']

# 학습 데이터와 테스트 데이터를 나눕니다.
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

X_train

       지역   공항    이름       대여일       반납일   크기  제한인원수   보험  브랜드
2986  2.0  3.0  20.0  20230827  20230828  4.0      5  0.0  2.0
1089  3.0  6.0   3.0  20230815  20230816  4.0      5  1.0  0.0
2942  2.0  3.0  35.0  20230822  20230823  4.0      5  2.0  7.0
485   4.0  4.0  20.0  20230809  20230810  4.0      5  0.0  2.0
2181  0.0  2.0  28.0  20230803  20230804  7.0      5  0.0  2.0
...   ...  ...   ...       ...       ...  ...    ...  ...  ...
1130  3.0  6.0  16.0  20230819  20230820  0.0      7  1.0  7.0
1294  3.0  6.0  23.0  20230906  20230907  4.0      5  1.0  2.0
860   4.0  4.0  36.0  20230923  20230924  0.0     10  0.0  2.0
3507  1.0  0.0  35.0  20230902  20230903  4.0      5  2.0  7.0
3174  2.0  3.0  25.0  20230917  20230918  2.0      5  1.0  6.0

[3007 rows x 9 columns]

In [42]:
# 랜덤 포레스트 모델을 생성하고 학습합니다.
rf_model = RandomForestRegressor(random_state=42)
rf_model.fit(X_train, y_train)

# 테스트 데이터로 예측을 수행합니다.
y_pred = rf_model.predict(X_test)

# R-squared 값을 계산합니다.
r2 = r2_score(y_test, y_pred)
print("R-squared:", r2)

R-squared: 0.9553708045514018

In [43]:
import joblib
# 학습한 모델을 피클링하여 저장합니다.
joblib.dump(rf_model, 'car_rf_model.pkl')

['car_rf_model.pkl']