In [62]:
import pandas as pd
df1 = pd.read_csv('hotel_list_TO_9.csv')
df1

,호텔명,입실,퇴실,지역,숙박유형,별점,등급,가격
0,신주쿠 워싱턴 호텔 도쿄 메인,2023-09-01,2023-09-02,도쿄,호텔,7.4,3성급,89677
1,호텔 그레이스리 신주쿠,2023-09-01,2023-09-02,도쿄,호텔,8.6,4성급,142305
2,호텔 그레이스리 긴자,2023-09-01,2023-09-02,도쿄,호텔,8.2,4성급,97923
3,포 시즌스 호텔 도쿄 앳 오테마치,2023-09-01,2023-09-02,도쿄,호텔,9.0,5성급,976200
4,게이오 플라자 호텔 도쿄,2023-09-01,2023-09-02,도쿄,호텔,8.4,4성급,190251
...,...,...,...,...,...,...,...,...
5519,이마자토 료칸,2023-09-29,2023-09-30,오사카,"리조트,펜션,료칸",8.4,2성급,30503
5520,호텔 발리 언 리조트 신사이바시 (성인 전용),2023-09-29,2023-09-30,오사카,"리조트,펜션,료칸",8.5,2성급,164492
5521,야마토야 혼텐 료칸 오사카,2023-09-30,2023-10-01,오사카,"리조트,펜션,료칸",7.8,3성급,197790
5522,이마자토 료칸,2023-09-30,2023-10-01,오사카,"리조트,펜션,료칸",8.4,2성급,34162
5523,호텔 발리 언 리조트 신사이바시 (성인 전용),2023-09-30,2023-10-01,오사카,"리조트,펜션,료칸",8.5,2성급,220194

In [63]:
df2 = pd.read_csv("hotel_list_TO_78.csv")
df2

,호텔명,입실,퇴실,지역,숙박유형,별점,등급,가격
0,신주쿠 워싱턴 호텔 도쿄 메인,2023-07-25,2023-07-26,도쿄,호텔,7.4,3성급,87212
1,호텔 그레이스리 신주쿠,2023-07-25,2023-07-26,도쿄,호텔,8.6,4성급,154668
2,호텔 그레이스리 긴자,2023-07-25,2023-07-26,도쿄,호텔,8.2,4성급,114029
3,포 시즌스 호텔 도쿄 앳 오테마치,2023-07-25,2023-07-26,도쿄,호텔,9.0,5성급,1754224
4,게이오 플라자 호텔 도쿄,2023-07-25,2023-07-26,도쿄,호텔,8.4,4성급,550512
...,...,...,...,...,...,...,...,...
7087,이마자토 료칸,2023-08-30,2023-08-31,오사카,"리조트,펜션,료칸",8.4,2성급,30503
7088,호텔 발리 언 리조트 신사이바시 (성인 전용),2023-08-30,2023-08-31,오사카,"리조트,펜션,료칸",8.5,2성급,86337
7089,야마토야 혼텐 료칸 오사카,2023-08-31,2023-09-01,오사카,"리조트,펜션,료칸",7.8,3성급,145046
7090,이마자토 료칸,2023-08-31,2023-09-01,오사카,"리조트,펜션,료칸",8.4,2성급,31217
7091,호텔 발리 언 리조트 신사이바시 (성인 전용),2023-08-31,2023-09-01,오사카,"리조트,펜션,료칸",8.5,2성급,86337

In [64]:
df_sum1 = pd.concat([df2, df1])
df_sum1

,호텔명,입실,퇴실,지역,숙박유형,별점,등급,가격
0,신주쿠 워싱턴 호텔 도쿄 메인,2023-07-25,2023-07-26,도쿄,호텔,7.4,3성급,87212
1,호텔 그레이스리 신주쿠,2023-07-25,2023-07-26,도쿄,호텔,8.6,4성급,154668
2,호텔 그레이스리 긴자,2023-07-25,2023-07-26,도쿄,호텔,8.2,4성급,114029
3,포 시즌스 호텔 도쿄 앳 오테마치,2023-07-25,2023-07-26,도쿄,호텔,9.0,5성급,1754224
4,게이오 플라자 호텔 도쿄,2023-07-25,2023-07-26,도쿄,호텔,8.4,4성급,550512
...,...,...,...,...,...,...,...,...
5519,이마자토 료칸,2023-09-29,2023-09-30,오사카,"리조트,펜션,료칸",8.4,2성급,30503
5520,호텔 발리 언 리조트 신사이바시 (성인 전용),2023-09-29,2023-09-30,오사카,"리조트,펜션,료칸",8.5,2성급,164492
5521,야마토야 혼텐 료칸 오사카,2023-09-30,2023-10-01,오사카,"리조트,펜션,료칸",7.8,3성급,197790
5522,이마자토 료칸,2023-09-30,2023-10-01,오사카,"리조트,펜션,료칸",8.4,2성급,34162
5523,호텔 발리 언 리조트 신사이바시 (성인 전용),2023-09-30,2023-10-01,오사카,"리조트,펜션,료칸",8.5,2성급,220194

In [65]:
df3 = pd.read_csv("hotel_list_SOF_9.csv")
df3

,호텔명,입실,퇴실,지역,숙박유형,별점,등급,가격
0,게이오 플라자 호텔 삿포로,2023-09-01,2023-09-02,삿포로,호텔,8.6,4성급,160468
1,라젠트 스테이 삿포로 오도리 홋카이도,2023-09-01,2023-09-02,삿포로,호텔,8.7,3성급,118158
2,더 놋 삿포로,2023-09-01,2023-09-02,삿포로,호텔,8.7,3성급,230280
3,호텔 그레이스리 삿포로,2023-09-01,2023-09-02,삿포로,호텔,8.1,3성급,213579
4,JR 타워 호텔 닛코 삿포로,2023-09-01,2023-09-02,삿포로,호텔,8.8,4성급,372549
...,...,...,...,...,...,...,...,...
11500,하마코야,2023-09-30,2023-10-01,후쿠오카,"리조트,펜션,료칸",9.2,2성급,185716
11501,더 루이간스 스파 & 리조트,2023-09-30,2023-10-01,후쿠오카,"리조트,펜션,료칸",8.5,4성급,243337
11502,웰캐빈 나카수 (남성 전용),2023-09-30,2023-10-01,후쿠오카,"리조트,펜션,료칸",8.9,2성급,26934
11503,야마모토 료칸 후쿠오카,2023-09-30,2023-10-01,후쿠오카,"리조트,펜션,료칸",7.4,2성급,90104
11504,큐카무라 시카노시마,2023-09-30,2023-10-01,후쿠오카,"리조트,펜션,료칸",8.1,3성급,166316

In [66]:
df4 = pd.read_csv("hotel_list_SOF_78.csv")
df4

,호텔명,입실,퇴실,지역,숙박유형,별점,등급,가격
0,게이오 플라자 호텔 삿포로,2023-07-25,2023-07-26,삿포로,호텔,8.6,4성급,299676
1,라젠트 스테이 삿포로 오도리 홋카이도,2023-07-25,2023-07-26,삿포로,호텔,8.7,3성급,182711
2,호텔 그레이스리 삿포로,2023-07-25,2023-07-26,삿포로,호텔,8.1,3성급,125629
3,삿포로 그랜드 호텔,2023-07-25,2023-07-26,삿포로,호텔,8.3,4성급,186283
4,로이톤 삿포로 호텔,2023-07-25,2023-07-26,삿포로,호텔,8.0,4성급,142069
...,...,...,...,...,...,...,...,...
15754,하마코야,2023-08-31,2023-09-01,후쿠오카,"리조트,펜션,료칸",9.2,2성급,185361
15755,더 루이간스 스파 & 리조트,2023-08-31,2023-09-01,후쿠오카,"리조트,펜션,료칸",8.5,4성급,115225
15756,웰캐빈 나카수 (남성 전용),2023-08-31,2023-09-01,후쿠오카,"리조트,펜션,료칸",8.9,2성급,24187
15757,야마모토 료칸 후쿠오카,2023-08-31,2023-09-01,후쿠오카,"리조트,펜션,료칸",7.4,2성급,28236
15758,큐카무라 시카노시마,2023-08-31,2023-09-01,후쿠오카,"리조트,펜션,료칸",8.1,3성급,148203

In [67]:
df_sum2 = pd.concat([df4, df3])
df_sum2

,호텔명,입실,퇴실,지역,숙박유형,별점,등급,가격
0,게이오 플라자 호텔 삿포로,2023-07-25,2023-07-26,삿포로,호텔,8.6,4성급,299676
1,라젠트 스테이 삿포로 오도리 홋카이도,2023-07-25,2023-07-26,삿포로,호텔,8.7,3성급,182711
2,호텔 그레이스리 삿포로,2023-07-25,2023-07-26,삿포로,호텔,8.1,3성급,125629
3,삿포로 그랜드 호텔,2023-07-25,2023-07-26,삿포로,호텔,8.3,4성급,186283
4,로이톤 삿포로 호텔,2023-07-25,2023-07-26,삿포로,호텔,8.0,4성급,142069
...,...,...,...,...,...,...,...,...
11500,하마코야,2023-09-30,2023-10-01,후쿠오카,"리조트,펜션,료칸",9.2,2성급,185716
11501,더 루이간스 스파 & 리조트,2023-09-30,2023-10-01,후쿠오카,"리조트,펜션,료칸",8.5,4성급,243337
11502,웰캐빈 나카수 (남성 전용),2023-09-30,2023-10-01,후쿠오카,"리조트,펜션,료칸",8.9,2성급,26934
11503,야마모토 료칸 후쿠오카,2023-09-30,2023-10-01,후쿠오카,"리조트,펜션,료칸",7.4,2성급,90104
11504,큐카무라 시카노시마,2023-09-30,2023-10-01,후쿠오카,"리조트,펜션,료칸",8.1,3성급,166316

In [68]:
df=pd.concat([df_sum1, df_sum2])
df

,호텔명,입실,퇴실,지역,숙박유형,별점,등급,가격
0,신주쿠 워싱턴 호텔 도쿄 메인,2023-07-25,2023-07-26,도쿄,호텔,7.4,3성급,87212
1,호텔 그레이스리 신주쿠,2023-07-25,2023-07-26,도쿄,호텔,8.6,4성급,154668
2,호텔 그레이스리 긴자,2023-07-25,2023-07-26,도쿄,호텔,8.2,4성급,114029
3,포 시즌스 호텔 도쿄 앳 오테마치,2023-07-25,2023-07-26,도쿄,호텔,9.0,5성급,1754224
4,게이오 플라자 호텔 도쿄,2023-07-25,2023-07-26,도쿄,호텔,8.4,4성급,550512
...,...,...,...,...,...,...,...,...
11500,하마코야,2023-09-30,2023-10-01,후쿠오카,"리조트,펜션,료칸",9.2,2성급,185716
11501,더 루이간스 스파 & 리조트,2023-09-30,2023-10-01,후쿠오카,"리조트,펜션,료칸",8.5,4성급,243337
11502,웰캐빈 나카수 (남성 전용),2023-09-30,2023-10-01,후쿠오카,"리조트,펜션,료칸",8.9,2성급,26934
11503,야마모토 료칸 후쿠오카,2023-09-30,2023-10-01,후쿠오카,"리조트,펜션,료칸",7.4,2성급,90104
11504,큐카무라 시카노시마,2023-09-30,2023-10-01,후쿠오카,"리조트,펜션,료칸",8.1,3성급,166316

In [69]:
df.duplicated().sum()

3589

In [70]:
df = df.drop_duplicates()

In [71]:
#인덱스 재정렬
df.reset_index(drop=True, inplace=True)
df

,호텔명,입실,퇴실,지역,숙박유형,별점,등급,가격
0,신주쿠 워싱턴 호텔 도쿄 메인,2023-07-25,2023-07-26,도쿄,호텔,7.4,3성급,87212
1,호텔 그레이스리 신주쿠,2023-07-25,2023-07-26,도쿄,호텔,8.6,4성급,154668
2,호텔 그레이스리 긴자,2023-07-25,2023-07-26,도쿄,호텔,8.2,4성급,114029
3,포 시즌스 호텔 도쿄 앳 오테마치,2023-07-25,2023-07-26,도쿄,호텔,9.0,5성급,1754224
4,게이오 플라자 호텔 도쿄,2023-07-25,2023-07-26,도쿄,호텔,8.4,4성급,550512
...,...,...,...,...,...,...,...,...
36286,하마코야,2023-09-30,2023-10-01,후쿠오카,"리조트,펜션,료칸",9.2,2성급,185716
36287,더 루이간스 스파 & 리조트,2023-09-30,2023-10-01,후쿠오카,"리조트,펜션,료칸",8.5,4성급,243337
36288,웰캐빈 나카수 (남성 전용),2023-09-30,2023-10-01,후쿠오카,"리조트,펜션,료칸",8.9,2성급,26934
36289,야마모토 료칸 후쿠오카,2023-09-30,2023-10-01,후쿠오카,"리조트,펜션,료칸",7.4,2성급,90104
36290,큐카무라 시카노시마,2023-09-30,2023-10-01,후쿠오카,"리조트,펜션,료칸",8.1,3성급,166316

In [72]:
# DataFrame을 CSV 파일로 저장
df.to_csv('hotel.csv', index=False, encoding='utf-8-sig')

In [73]:
import pandas as pd
df = pd.read_csv('hotel_total_final.csv')
df

,호텔명,입실,퇴실,지역,숙박유형,별점,등급,가격,가장 가까운 공항,가장 가까운 공항과의 거리,가장 가까운 공항까지 시간
0,신주쿠 워싱턴 호텔 도쿄 메인,2023-07-25,2023-07-26,도쿄,호텔,7.4,3성급,87212,Tokyo International Airport,22.2 km,29 mins
1,호텔 그레이스리 신주쿠,2023-07-25,2023-07-26,도쿄,호텔,8.6,4성급,154668,Tokyo International Airport,23.7 km,36 mins
2,호텔 그레이스리 긴자,2023-07-25,2023-07-26,도쿄,호텔,8.2,4성급,114029,Tokyo International Airport,19.7 km,24 mins
3,포 시즌스 호텔 도쿄 앳 오테마치,2023-07-25,2023-07-26,도쿄,호텔,9.0,5성급,1754224,Tokyo International Airport,23.0 km,25 mins
4,게이오 플라자 호텔 도쿄,2023-07-25,2023-07-26,도쿄,호텔,8.4,4성급,550512,Tokyo International Airport,22.5 km,31 mins
...,...,...,...,...,...,...,...,...,...,...,...
30478,웰캐빈 나카수 (남성 전용),2023-09-29,2023-09-30,후쿠오카,"리조트,펜션,료칸",8.9,2성급,24846,Fukuoka Airport,5.3 km,11 mins
30479,야마모토 료칸 후쿠오카,2023-09-29,2023-09-30,후쿠오카,"리조트,펜션,료칸",7.4,2성급,31414,Fukuoka Airport,4.1 km,14 mins
30480,웰캐빈 나카수 (남성 전용),2023-09-30,2023-10-01,후쿠오카,"리조트,펜션,료칸",8.9,2성급,26934,Fukuoka Airport,5.3 km,11 mins
30481,야마모토 료칸 후쿠오카,2023-09-30,2023-10-01,후쿠오카,"리조트,펜션,료칸",7.4,2성급,90104,Fukuoka Airport,4.1 km,14 mins
30482,큐카무라 시카노시마,2023-09-30,2023-10-01,후쿠오카,"리조트,펜션,료칸",8.1,3성급,166316,Fukuoka Airport,27.7 km,37 mins

In [74]:
#6천개 정도의 데이터가 사라졌음 왜일까?
df.duplicated().sum()

0

In [75]:
df['가격'].min()

5902

In [76]:
# Assuming you have a DataFrame called 'data'
cols = ['지역', '숙박유형','가장 가까운 공항']

# Print unique values for each column in 'data'
for col in cols:
    unique_values = df[col].unique()
    unique_values.sort()  # Sort the unique values for each column
    print(f"Unique values in '{col}': {unique_values}")

Unique values in '지역': ['도쿄' '삿포로' '오사카' '오키나와' '후쿠오카']
Unique values in '숙박유형': ['게스트하우스,캡슐호텔,호스텔' '리조트,펜션,료칸' '호텔']
Unique values in '가장 가까운 공항': ['Fukuoka Airport' 'Kansai International Airport' 'Naha Airport'
 'New Chitose Airport' 'Tokyo International Airport']

In [77]:
df.describe()

                 가격
count  3.048300e+04
mean   1.462481e+05
std    1.564572e+05
min    5.902000e+03
25%    6.231100e+04
50%    1.035000e+05
75%    1.721865e+05
max    4.081181e+06

In [78]:
# 거리 인코딩 함수 정의
def encode_distance(distance):
    if distance <= 20:
        return 0
    elif distance <= 50:
        return 1
    else:
        return 2

# 시간 인코딩 함수 정의
def encode_time(time):
    if time <= 25:
        return 0
    elif time <= 40:
        return 1
    else:
        return 2

In [79]:
from sklearn.preprocessing import OrdinalEncoder
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_squared_error, r2_score

# 호텔명 컬럼 삭제
df.drop(columns=['호텔명','가장 가까운 공항','가장 가까운 공항과의 거리'], inplace=True)

# 입실과 퇴실 날짜 형식 정리하기
df['입실'] = pd.to_datetime(df['입실']).dt.strftime('%Y%m%d').astype(int)
df['퇴실'] = pd.to_datetime(df['퇴실']).dt.strftime('%Y%m%d').astype(int)
# 오디널 인코딩하기
encoder = OrdinalEncoder()
df[['지역', '숙박유형']] = encoder.fit_transform(df[['지역', '숙박유형']])

df['등급'] = df['등급'].str.extract(r'(\d+)').astype(int)
df['가장 가까운 공항까지 시간'] = df['가장 가까운 공항까지 시간'].str.extract(r'(\d+)').astype(int)
# Convert '평점없음' to NaN
df['별점'] = pd.to_numeric(df['별점'], errors='coerce')

# Calculate the mode (most frequent value) of the '별점' column excluding NaN values
mode_star_rating = df['별점'].mode().values[0]

# Fill NaN values with the calculated mode
df['별점'].fillna(mode_star_rating, inplace=True)

# 트레인과 테스트 세트로 나누기
X = df.drop(columns=['가격'])
y = df['가격']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
X_train

             입실        퇴실   지역  숙박유형   별점  등급  가장 가까운 공항까지 시간
25143  20230918  20230919  3.0   2.0  8.3   3              11
8513   20230922  20230923  0.0   2.0  8.6   4              36
14160  20230818  20230819  1.0   1.0  8.6   4               1
1192   20230806  20230807  0.0   2.0  8.4   4              31
7278   20230907  20230908  0.0   2.0  7.6   3              24
...         ...       ...  ...   ...  ...  ..             ...
29802  20230928  20230929  4.0   2.0  8.9   3              11
5390   20230803  20230804  2.0   2.0  8.2   5              48
860    20230802  20230803  0.0   2.0  8.7   3              32
15795  20230818  20230819  3.0   2.0  8.6   3              15
23654  20230929  20230930  1.0   2.0  8.8   3              57

[24386 rows x 7 columns]

In [80]:
df.describe()

,입실,퇴실,지역,숙박유형,별점,등급,가격,가장 가까운 공항까지 시간
count,3.048300e+04,3.048300e+04,30483.000000,30483.000000,30483.000000,30483.000000,3.048300e+04,30483.000000
mean,2.023085e+07,2.023086e+07,1.950497,1.619263,8.305725,3.088279,1.462481e+05,26.990224
std,6.366633e+01,6.419003e+01,1.557657,0.721350,0.599054,0.890086,1.564572e+05,17.184347
min,2.023072e+07,2.023073e+07,0.000000,0.000000,5.200000,1.000000,5.902000e+03,1.000000
25%,2.023081e+07,2.023081e+07,0.000000,2.000000,8.000000,3.000000,6.231100e+04,12.000000
50%,2.023083e+07,2.023083e+07,2.000000,2.000000,8.400000,3.000000,1.035000e+05,24.000000
75%,2.023091e+07,2.023092e+07,3.000000,2.000000,8.700000,4.000000,1.721865e+05,40.000000
max,2.023093e+07,2.023100e+07,4.000000,2.000000,10.000000,5.000000,4.081181e+06,59.000000

In [81]:
# 랜덤 포레스트 모델 훈련 및 평가하기
rf_model = RandomForestRegressor(random_state=42)
rf_model.fit(X_train, y_train)

y_pred = rf_model.predict(X_test)

mse = mean_squared_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)

print(f'Mean Squared Error (MSE): {mse}')
print(f'R-squared (R2): {r2}')

Mean Squared Error (MSE): 4957258449.551323
R-squared (R2): 0.7936335495818256

In [82]:
import joblib
# 학습한 모델을 피클링하여 저장합니다.
joblib.dump(rf_model, 'hotel_rf_model.pkl')

['hotel_rf_model.pkl']